#IMAGEM DE ORIGEM
FROM ubuntu:14.04
MAINTAINER Matheus Fidelis <msfidelis01@gmail.com>

#COMANDOS PARA COSNTRUÇÃO E INSTALAÇÃO DOS PACOTES
RUN apt-get update ; apt-get install -y apache2 php5 

#COMPARTILHAMENTO DE VOLUME
VOLUME /var/www/html/

#SETANDO AS VARIÁVEIS DE AMBIENTE
RUN a2enmod rewrite
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

#EXPONDO UMA PORTA 
EXPOSE 80

#COMANDO QUE A IMAGEM IRÁ EXECUTAR DURANTE A INICIALIZAÇÃO
CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]



